DROP DATABASE IF EXISTS PROJELITE;
CREATE DATABASE PROJELITE;
USE PROJELITE;

-- table users 
CREATE TABLE USERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

-- table employee 
CREATE TABLE EMPLOYEE (
    IDEMPLOYEE INT AUTO_INCREMENT PRIMARY KEY,
    IDUSER INT NOT NULL,  
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    ROLE VARCHAR(255),
    FOREIGN KEY (IDUSER) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- table project 
CREATE TABLE PROJECT (
    IDPROJECT INT AUTO_INCREMENT PRIMARY KEY,
    IDUSER INT NOT NULL, 
    DESCRIPTION TEXT,
    NAME_PROJECT VARCHAR(255),
    IDEMPLOYEE INT,
    FOREIGN KEY (IDUSER) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (IDEMPLOYEE) REFERENCES EMPLOYEE(IDEMPLOYEE) ON DELETE SET NULL
);

-- table task 
CREATE TABLE TASK (
    IDTASK INT AUTO_INCREMENT PRIMARY KEY,
    IDUSER INT NOT NULL,  
    IDEMPLOYEE INT,
    IDPROJECT INT,
    TASK_NAME VARCHAR(255),
    DESCRIPTION TEXT,
    ESTADO VARCHAR(255),
    FOREIGN KEY (IDUSER) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (IDEMPLOYEE) REFERENCES EMPLOYEE(IDEMPLOYEE) ON DELETE SET NULL,
    FOREIGN KEY (IDPROJECT) REFERENCES PROJECT(IDPROJECT) ON DELETE CASCADE
);