DROP DATABASE IF EXISTS PROJELITE;
CREATE DATABASE PROJELITE;
USE PROJELITE;

-- table users
CREATE TABLE USERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

-- table employee
CREATE TABLE EMPLOYEE (
    IDEMPLOYEE INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    ROLE VARCHAR(255)
);

-- table project
CREATE TABLE PROJECT (
    IDPROJECT INT AUTO_INCREMENT PRIMARY KEY,
    NAME_PROJECT VARCHAR(255),
    IDEMPLOYEE INT,
    FOREIGN KEY (IDEMPLOYEE) REFERENCES EMPLOYEE(IDEMPLOYEE) ON DELETE SET NULL
);

-- table task
CREATE TABLE TASK (
    IDTASK INT AUTO_INCREMENT PRIMARY KEY,
    IDEMPLOYEE INT,
    IDPROJECT INT,
    TASK_NAME VARCHAR(255),
    FOREIGN KEY (IDEMPLOYEE) REFERENCES EMPLOYEE(IDEMPLOYEE) ON DELETE SET NULL,
    FOREIGN KEY (IDPROJECT) REFERENCES PROJECT(IDPROJECT) ON DELETE CASCADE
);