CREATE DATABASE PROJELITE;

USE PROJELITE;

-- table users
CREATE TABLE USERS (
    ID INT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

-- table employee

CREATE TABLE EMPLOYEE (
    IDEMPLOYEE INT PRIMARY KEY,
    NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    ROLE VARCHAR(255)
);

-- table project
 
CREATE TABLE PROJECT (
    IDPROJECT INT PRIMARY KEY,
    NAME_PROJECT VARCHAR(255),
    IDEMPLOYEE INT,
    FOREIGN KEY (IDEMPLOYEE) REFERENCES EMPLOYEE(IDEMPLOYEE)
);

-- table task
CREATE TABLE TASK (
    IDTASK INT PRIMARY KEY,
    IDEMPLOYEE INT,
    IDPROJECT INT,
    TASK_NAME VARCHAR(255),
    FOREIGN KEY (IDEMPLOYEE) REFERENCES EMPLOYEE(IDEMPLOYEE),
    FOREIGN KEY (IDPROJECT) REFERENCES PROJECT(IDPROJECT)
);


-- GetTasksByEmployee
DELIMITER //

CREATE PROCEDURE GetTasksByEmployee(IN emp_id INT)
BEGIN
    SELECT 
        t.TASK_NAME,
        p.NAME_PROJECT
    FROM TASK t
    JOIN PROJECT p ON t.IDPROJECT = p.IDPROJECT
    WHERE t.IDEMPLOYEE = emp_id;
END //

DELIMITER ;

-- GetProjects
DELIMITER //

CREATE PROCEDURE GetProjects()
BEGIN
    SELECT 
        p.NAME_PROJECT
    FROM TASK t
    JOIN PROJECT p ON t.IDPROJECT = p.IDPROJECT;
END //

DELIMITER ;

